remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Ambel - A Chisel3 Library for Generating AMBA Components
description: This site hosts the ScalaDocs and Verilator coverage reports for Ambel
